### ISSUE TITLE
Optionally resolve string values given via %key

### ISSUE THREAD

**Issue by kwin** [jsedding/osgi-ds-metatype-diff#5]
By default the maven-scr-plugin generates values for the metatypes by just placing a key in the XML which just references the value from the according i18n properties file.
Since this is not supported by either maven-bundle-plugin nor bnd-maven-plugin (https://github.com/bndtools/bnd/issues/1905) for comparison purposes it would be nice to compare with the value from the i18n properties file.

For that all values starting with `%` should be looked up from the properties file.

**Comment by jsedding** [comment]
I like this enhancement in particular. Thanks!
