### ISSUE TITLE
DS Property without value is not being emitted

### ISSUE THREAD

**Issue by kwin** [jsedding/osgi-ds-metatype-diff#7]
If I have a DS XML File like this
```
<?xml version="1.0" encoding="UTF-8"?><components xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0">
    <scr:component immediate="true" name="biz.netcentric.cq.tools.actool.configuploadlistener.impl.UploadListenerServiceImpl" activate="activate" deactivate="deactivate">
        <implementation class="biz.netcentric.cq.tools.actool.configuploadlistener.impl.UploadListenerServiceImpl"/>
        <service servicefactory="false">
            <provide interface="biz.netcentric.cq.tools.actool.configuploadlistener.UploadListenerService"/>
        </service>
        <property name="AceUploadListener.setStatusService"/>
        ...
```

Then the property `AceUploadListener.setStatusService` is not being considered in the PrintingVisitor.

**Comment by kwin** [comment]
The problem is that currently there is no visual difference between a map not containing a key or containing a key with a `null` value. Semantically that makes a difference though.

**Comment by jsedding** [comment]
Is it a semantic difference in SCR when a property has no value and when it is not present at all? If it is semantically different, then it should definitely be shown as a diff. If there is no semantic difference, I would still consider including it. WDYT @kwin ? PR welcome :)

**Comment by kwin** [comment]
Well actually it is stated in OSGi Compendium R7 in chapter 112.4.6 (Property and Property Elements): 
> If the value attribute is not specified, the body of the property element must
contain one or more values.

So it seems my example is just invalid (it is a shame that maven-scr-plugin did emit those invalid component descriptions). So I think it is reasonable to close this issue.

**Comment by jsedding** [comment]
Thanks @kwin for checking the spec. Let's close the issue then. If you feel later that we should address the issue, please re-open.
