### ISSUE TITLE
Allow to (optionally) continue comparison even in case of parsing issues with metatype or ds xmls 

### ISSUE THREAD

**Issue by kwin** [jsedding/osgi-ds-metatype-diff#9]
In the past we had issues where either the metadata or the ds xml was invalid and the parser has thrown exception due to that (e.g. in #8 or #1). This exception was not caught and prevented the program from continuing with the comparison.

To still allow to compare the other (valid) metadata it would be nice to have a flag which allows to just skip this xml in case of failures and continue with the next one. Of course there should be a pretty obvious log statement in that case.

**Comment by jsedding** [comment]
@kwin I have changed the code to log warnings instead of throw exceptions. I have not made this behaviour optional. If that satisfies your need, please close the issue. Otherwise feel free to submit a PR implementing an optional switch.

**Comment by kwin** [comment]
Works now, thanks.
